In [6]:
import pandas as pd

In [10]:
df = pd.read_csv("diamonds.csv")
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [12]:
specific_data = df[['carat', 'cut', 'color']]
print(specific_data)

       carat        cut color
0       0.23      Ideal     E
1       0.21    Premium     E
2       0.23       Good     E
3       0.29    Premium     I
4       0.31       Good     J
...      ...        ...   ...
53935   0.72      Ideal     D
53936   0.72       Good     D
53937   0.70  Very Good     D
53938   0.86    Premium     H
53939   0.75      Ideal     D

[53940 rows x 3 columns]

In [13]:
specific_row = df[5:50]
print(specific_row)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39
10,11,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
11,12,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
17,18,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70
18,19,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71
19,20,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66
20,21,0.30,Good,I,SI2,63.3,56.0,351,4.26,4.30,2.71
21,22,0.23,Very Good,E,VS2,63.8,55.0,352,3.85,3.92,2.48
22,23,0.23,Very Good,H,VS1,61.0,57.0,353,3.94,3.96,2.41
23,24,0.31,Very Good,J,SI1,59.4,62.0,353,4.39,4.43,2.62
24,25,0.31,Very Good,J,SI1,58.1,62.0,353,4.44,4.47,2.59
25,26,0.23,Very Good,G,VVS2,60.4,58.0,354,3.97,4.01,2.41
26,27,0.24,Premium,I,VS1,62.5,57.0,355,3.97,3.94,2.47
27,28,0.30,Very Good,J,VS2,62.2,57.0,357,4.28,4.30,2.67
28,29,0.23,Very Good,D,VS2,60.5,61.0,357,3.96,3.97,2.40
29,30,0.23,Very Good,F,VS1,60.9,57.0,357,3.96,3.99,2.42
30,31,0.23,Very Good,F,VS1,60.0,57.0,402,4.00,4.03,2.41
31,32,0.23,Very Good,F,VS1,59.8,57.0,402,4.04,4.06,2.42
32,33,0.23,Very Good,E,VS1,60.7,59.0,402,3.97,4.01,2.42
33,34,0.23,Very Good,E,VS1,59.5,58.0,402,4.01,4.06,2.40
34,35,0.23,Very Good,D,VS1,61.9,58.0,402,3.92,3.96,2.44
35,36,0.23,Good,F,VS1,58.2,59.0,402,4.06,4.08,2.37
36,37,0.23,Good,E,VS1,64.1,59.0,402,3.83,3.85,2.46
37,38,0.31,Good,H,SI1,64.0,54.0,402,4.29,4.31,2.75
38,39,0.26,Very Good,D,VS2,60.8,59.0,403,4.13,4.16,2.52
39,40,0.33,Ideal,I,SI2,61.8,55.0,403,4.49,4.51,2.78
40,41,0.33,Ideal,I,SI2,61.2,56.0,403,4.49,4.50,2.75
41,42,0.33,Ideal,J,SI1,61.1,56.0,403,4.49,4.55,2.76
42,43,0.26,Good,D,VS2,65.2,56.0,403,3.99,4.02,2.61
43,44,0.26,Good,D,VS1,58.4,63.0,403,4.19,4.24,2.46
44,45,0.32,Good,H,SI2,63.1,56.0,403,4.34,4.37,2.75
45,46,0.29,Premium,F,SI1,62.4,58.0,403,4.24,4.26,2.65
46,47,0.32,Very Good,H,SI2,61.8,55.0,403,4.35,4.42,2.71
47,48,0.32,Good,H,SI2,63.8,56.0,403,4.36,4.38,2.79
48,49,0.25,Very Good,E,VS2,63.3,60.0,404,4.00,4.03,2.54
49,50,0.29,Very Good,H,SI2,60.7,60.0,404,4.33,4.37,2.64

In [21]:
row_fetching_with_iloc = df.iloc[5:50]
#print(row_fetching_with_iloc)
row_fetching_with_iloc_col = df.iloc[5:50,2]
#print(row_fetching_with_iloc_col)
row_fetching_with_iloc_col_list = df.iloc[5:50,[2,4]]
print(row_fetching_with_iloc_col_list)

          cut clarity
5   Very Good    VVS2
6   Very Good    VVS1
7   Very Good     SI1
8        Fair     VS2
9   Very Good     VS1
10       Good     SI1
11      Ideal     VS1
12    Premium     SI1
13      Ideal     SI2
14    Premium     SI2
15    Premium      I1
16      Ideal     SI2
17       Good     SI1
18       Good     SI1
19  Very Good     SI1
20       Good     SI2
21  Very Good     VS2
22  Very Good     VS1
23  Very Good     SI1
24  Very Good     SI1
25  Very Good    VVS2
26    Premium     VS1
27  Very Good     VS2
28  Very Good     VS2
29  Very Good     VS1
30  Very Good     VS1
31  Very Good     VS1
32  Very Good     VS1
33  Very Good     VS1
34  Very Good     VS1
35       Good     VS1
36       Good     VS1
37       Good     SI1
38  Very Good     VS2
39      Ideal     SI2
40      Ideal     SI2
41      Ideal     SI1
42       Good     VS2
43       Good     VS1
44       Good     SI2
45    Premium     SI1
46  Very Good     SI2
47       Good     SI2
48  Very Good     VS2
49  Very Good     SI2

In [18]:
row_fetching_with_loc = df.loc[5:50]
#print(row_fetching_with_iloc)
row_fetching_with_loc_col = df.loc[5:50,'carat']
print(row_fetching_with_iloc_col)

5     Very Good
6     Very Good
7     Very Good
8          Fair
9     Very Good
10         Good
11        Ideal
12      Premium
13        Ideal
14      Premium
15      Premium
16        Ideal
17         Good
18         Good
19    Very Good
20         Good
21    Very Good
22    Very Good
23    Very Good
24    Very Good
25    Very Good
26      Premium
27    Very Good
28    Very Good
29    Very Good
30    Very Good
31    Very Good
32    Very Good
33    Very Good
34    Very Good
35         Good
36         Good
37         Good
38    Very Good
39        Ideal
40        Ideal
41        Ideal
42         Good
43         Good
44         Good
45      Premium
46    Very Good
47         Good
48    Very Good
49    Very Good
Name: cut, dtype: object